---
# Include vars based on different criteria
- name: Include vars based on system
  include_vars: "{{ vars_file }}"
  with_fileglob:
    - "vars/*-{{ ansible_system }}.yml"
  loop_control:
    loop_var: vars_file

- name: Include vars based on os family
  include_vars: "{{ vars_file }}"
  with_fileglob:
    - "vars/*-{{ ansible_os_family }}.yml"
  loop_control:
    loop_var: vars_file

- name: Include vars based on distribution
  include_vars: "{{ vars_file }}"
  with_fileglob:
    - "vars/*-{{ ansible_distribution }}.yml"
  loop_control:
    loop_var: vars_file

# Include tasks based on different criteria
- name: Include tasks based on system
  include_tasks: "{{ tasks_file }}"
  with_fileglob:
    - "tasks/*-{{ ansible_system }}.yml"
  loop_control:
    loop_var: tasks_file

- name: Include tasks based on os family
  include_tasks: "{{ tasks_file }}"
  with_fileglob:
    - "tasks/*-{{ ansible_os_family }}.yml"
  loop_control:
    loop_var: tasks_file

- name: Include tasks based on distribution
  include_tasks: "{{ tasks_file }}"
  with_fileglob:
    - "tasks/*-{{ ansible_distribution }}.yml"
  loop_control:
    loop_var: tasks_file

- debug:
    var: name
