---
# Include variables and define needed variables.
- name: Include OS-family variables.
  include_vars: "*-{{ ansible_os_family }}.yml"

- name: Include OS-family tasks.
  include_vars: "*-{{ ansible_os_family }}.yml"

- debug:
    var: name
