---
# Include vars based on different criteria
- name: Include vars based on system
  ansible.builtin.include_vars: "{{ vars_file }}"
  with_fileglob:
    - "vars/{{ ansible_system }}.yml"
  loop_control:
    loop_var: vars_file

- name: Include vars based on os family
  ansible.builtin.include_vars: "{{ vars_file }}"
  with_fileglob:
    - "vars/{{ ansible_os_family }}.yml"
  loop_control:
    loop_var: vars_file

- name: Include vars based on distribution
  ansible.builtin.include_vars: "{{ vars_file }}"
  with_fileglob:
    - "vars/{{ ansible_distribution }}.yml"
  loop_control:
    loop_var: vars_file

- name: Include vars based on distribution version
  ansible.builtin.include_vars: "{{ vars_file }}"
  with_fileglob:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  loop_control:
    loop_var: vars_file

- name: Include vars based on distribution release
  ansible.builtin.include_vars: "{{ vars_file }}"
  with_fileglob:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  loop_control:
    loop_var: vars_file
