all:
	@docker build . -f Dockerfile.CentOS8 -t memoryleak/molecule:centos8
	@docker build . -f Dockerfile.CentOS7 -t memoryleak/molecule:centos7
	@docker build . -f Dockerfile.Focal -t memoryleak/molecule:focal
	@docker build . -f Dockerfile.Bionic -t memoryleak/molecule:bionic
