---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    - ansible_become_password: haferbrei123

  tasks:
    - name: Restore VM state
      shell: "/usr/bin/virsh snapshot-revert {{ item.instance }} PostInstall"
      become: true
      register: server
      with_items: "{{ molecule_yml.platforms }}"

    - when: server.changed | default(false) | bool
      block:
        - name: Populate instance config dict
          set_fact:
            instance_conf_dict: {
              'instance': "{{ item.instance }}",
              'address': "{{ item.address }}",
              'user': "{{ item.user | default('ansible')}}",
              'port': "{{ item.port | default(22)}}",
              'ansible_become_pass': "{{ item.become_pass | default('ansible')}}",
          }

          with_items: "{{ molecule_yml.platforms }}"
          register: instance_config_dict

        - name: Convert instance config dict to a list
          set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: "Print instance conf"
          debug:
            var: instance_conf
          tags:
            - debug

        - name: "Print molecule_instance_config"
          debug:
            var: molecule_instance_config
          tags:
            - debug

        - name: Dump instance config
          copy:
            content: |
              # Molecule managed

              {{ instance_conf | to_json | from_json | to_yaml }}
            mode: 0665
            dest: "{{ molecule_instance_config }}"
