---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
    requirements-file: collections.yml

driver:
  name: docker

platforms:
  - name: centos7
    image: docker.io/pycontribs/centos:7

  - name: centos8
    image: docker.io/pycontribs/centos:8

  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest

  - name: opensuse
    image: docker.io/pycontribs/opensuse:latest

  - name: fedora
    image: docker.io/pycontribs/fedora

provisioner:
  name: ansible
verifier:
  name: ansible
