---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
  - name: opensuse
    image: docker.io/pycontribs/opensuse:latest
    pre_build_image: true
  - name: fedora
    image: docker.io/pycontribs/fedora
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
